/**
 * Puzzle build — run: node client/src/puzzle/build-puzzles.mjs
 */
import { Chess } from "chess.js";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { GENERATED_PUZZLES } from "./puzzles-generated.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** @type {Array<object>} */
const BASE_PUZZLES = [];

const MIN_PLAYER_PLIES = 3;
const MAX_PLAYER_PLIES = 5;

function playerPlies(puzzle) {
  return Math.ceil(puzzle.solution.length / 2);
}

function requiresMate(puzzle) {
  if (puzzle.theme === "mate" || puzzle.theme === "sacrifice") return true;
  if (puzzle.prompt?.includes("รุมฆาต")) return true;
  if (puzzle.title?.includes("#")) return true;
  return false;
}

function validatePuzzle(puzzle) {
  const game = new Chess(puzzle.fen);
  const startTurn = game.turn();

  for (let i = 0; i < puzzle.solution.length; i++) {
    const expectedTurn =
      i % 2 === 0 ? startTurn : startTurn === "w" ? "b" : "w";
    if (game.turn() !== expectedTurn) {
      throw new Error(
        `${puzzle.id}: wrong side to move at ply ${i} (expected ${expectedTurn})`
      );
    }

    const step = puzzle.solution[i];
    const opts = { from: step.from, to: step.to };
    if (step.promotion) opts.promotion = step.promotion;

    const res = game.move(opts);
    if (!res) {
      throw new Error(
        `${puzzle.id}: illegal move ${step.from}-${step.to} at ply ${i}`
      );
    }
  }

  if (requiresMate(puzzle) && !game.isCheckmate()) {
    throw new Error(`${puzzle.id}: solution does not end in checkmate`);
  }

  const plies = playerPlies(puzzle);
  if (plies < MIN_PLAYER_PLIES || plies > MAX_PLAYER_PLIES) {
    throw new Error(
      `${puzzle.id}: need ${MIN_PLAYER_PLIES}-${MAX_PLAYER_PLIES} player moves, got ${plies}`
    );
  }
}

function puzzleKey(p) {
  return `${p.fen}|${JSON.stringify(p.solution)}`;
}

const byId = new Map();
const byKey = new Set();

for (const puzzle of [...GENERATED_PUZZLES, ...BASE_PUZZLES]) {
  const key = puzzleKey(puzzle);
  if (byKey.has(key) || byId.has(puzzle.id)) continue;
  validatePuzzle(puzzle);
  byId.set(puzzle.id, puzzle);
  byKey.add(key);
}

const PUZZLES = [...byId.values()];

if (PUZZLES.length < 50) {
  throw new Error(
    `Need at least 50 puzzles, got ${PUZZLES.length}. Add more to puzzles-generated.mjs`
  );
}

const out = `/**
 * Tactical puzzles — generated by build-puzzles.mjs (do not edit by hand)
 * Total: ${PUZZLES.length} puzzles
 */

export const puzzles = ${JSON.stringify(PUZZLES, null, 2)};

const STORAGE_KEY = "chess_puzzles_completed";

export function getCompletedPuzzles() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
  } catch {
    return [];
  }
}

export function markPuzzleComplete(puzzleId) {
  const done = getCompletedPuzzles();
  if (!done.includes(puzzleId)) {
    done.push(puzzleId);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(done));
  }
}

export function isPuzzleComplete(puzzleId) {
  return getCompletedPuzzles().includes(puzzleId);
}

export const THEME_LABELS = {
  mate: "รุมฆาต",
  fork: "ส้อม",
  pin: "พิน / เสียบ",
  tactic: "แท็กติก",
  sacrifice: "เสียสละ",
  promotion: "เดินเบี้ย",
};

export const DIFFICULTY_LABELS = {
  easy: "ง่าย",
  medium: "ปานกลาง",
  hard: "ยาก",
};
`;

writeFileSync(path.join(__dirname, "puzzles.js"), out, "utf8");
console.log(`Wrote ${PUZZLES.length} puzzles to puzzles.js`);
