/**
 * Tactical puzzles — generated by build-puzzles.mjs (do not edit by hand)
 * Total: 51 puzzles
 */

export const puzzles = [
  {
    "id": "rook-mate-a",
    "title": "เรือ a8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♜",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "เรือ a8",
    "solution": [
      {
        "from": "a1",
        "to": "a8"
      }
    ]
  },
  {
    "id": "rook-mate-d",
    "title": "เรือ d8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♜",
    "fen": "6k1/5ppp/8/8/8/8/4P1PP/3R2K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "เรือ d8",
    "solution": [
      {
        "from": "d1",
        "to": "d8"
      }
    ]
  },
  {
    "id": "queen-mate-h7",
    "title": "ควีน h7#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/8/5pp1/7Q/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "ควีน h7",
    "solution": [
      {
        "from": "h5",
        "to": "h7"
      }
    ]
  },
  {
    "id": "queen-mate-d8",
    "title": "ควีน d8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "ควีน d8",
    "solution": [
      {
        "from": "d1",
        "to": "d8"
      }
    ]
  },
  {
    "id": "queen-mate-b7",
    "title": "ควีน b7#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "1k6/1p6/8/8/8/8/6PP/1Q4K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "ควีน b7",
    "solution": [
      {
        "from": "b1",
        "to": "b7"
      }
    ]
  },
  {
    "id": "queen-mate-a8",
    "title": "ควีน a8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/8/6PP/Q5K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "ควีน a8",
    "solution": [
      {
        "from": "a1",
        "to": "a8"
      }
    ]
  },
  {
    "id": "queen-mate-e8",
    "title": "ควีน e8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/4Q1K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "ควีน e8",
    "solution": [
      {
        "from": "e1",
        "to": "e8"
      }
    ]
  },
  {
    "id": "queen-mate-f7",
    "title": "ควีน f7#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/6pp/8/5Q2/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "ควีน f7",
    "solution": [
      {
        "from": "f5",
        "to": "f7"
      }
    ]
  },
  {
    "id": "piece-mate-bh7",
    "title": "แท็กติก bh7",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "6k1/5ppp/8/8/8/3B4/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "d3→h7",
    "solution": [
      {
        "from": "d3",
        "to": "h7"
      }
    ]
  },
  {
    "id": "piece-mate-bf7",
    "title": "แท็กติก bf7",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "6k1/5ppp/8/8/2B5/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "c4→f7",
    "solution": [
      {
        "from": "c4",
        "to": "f7"
      }
    ]
  },
  {
    "id": "piece-mate-nf7",
    "title": "แท็กติก nf7",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "6rk/5ppp/8/6N1/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "g5→f7",
    "solution": [
      {
        "from": "g5",
        "to": "f7"
      }
    ]
  },
  {
    "id": "piece-mate-nh7",
    "title": "แท็กติก nh7",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "6k1/5ppp/5N2/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "f6→h7",
    "solution": [
      {
        "from": "f6",
        "to": "h7"
      }
    ]
  },
  {
    "id": "fork-nc7",
    "title": "ม้าส้อม c7",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "easy",
    "icon": "♞",
    "fen": "1k6/r7/8/1N6/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "ม้าส้อม c7",
    "solution": [
      {
        "from": "b5",
        "to": "c7"
      }
    ]
  },
  {
    "id": "fork-ne5",
    "title": "ม้าส้อม e5",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4k3/8/8/4r3/8/5N2/8/4K2R w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "ม้าส้อม e5",
    "solution": [
      {
        "from": "f3",
        "to": "e5"
      }
    ]
  },
  {
    "id": "fork-qd5",
    "title": "ควีน d5",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4r1k1/5ppp/8/8/3Q4/8/5PPP/5RK1 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "ควีน d5",
    "solution": [
      {
        "from": "d4",
        "to": "d5"
      }
    ]
  },
  {
    "id": "promo-e8q",
    "title": "เดินเบี้ย e8q",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/4P3/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "e7→e8",
    "solution": [
      {
        "from": "e7",
        "to": "e8",
        "promotion": "q"
      }
    ]
  },
  {
    "id": "promo-h8r",
    "title": "เดินเบี้ย h8r",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/7P/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "h7→h8",
    "solution": [
      {
        "from": "h7",
        "to": "h8",
        "promotion": "r"
      }
    ]
  },
  {
    "id": "promo-b8q",
    "title": "เดินเบี้ย b8q",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/1P6/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "b7→b8",
    "solution": [
      {
        "from": "b7",
        "to": "b8",
        "promotion": "q"
      }
    ]
  },
  {
    "id": "promo-c8q",
    "title": "เดินเบี้ย c8q",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/2P5/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "c7→c8",
    "solution": [
      {
        "from": "c7",
        "to": "c8",
        "promotion": "q"
      }
    ]
  },
  {
    "id": "mate2-rook-ladder",
    "title": "รุมฆาตเรือ 2 ตา",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♜",
    "fen": "1k6/1pp5/8/8/8/8/1PP5/2K2R2 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาตใน 2 ตา",
    "hint": "Rf8+",
    "solution": [
      {
        "from": "f1",
        "to": "f8"
      },
      {
        "from": "b8",
        "to": "a7"
      },
      {
        "from": "f8",
        "to": "c8"
      }
    ]
  },
  {
    "id": "tactic-sacrifice-qe8",
    "title": "เสียสละแล้วรุมฆาต",
    "theme": "sacrifice",
    "themeLabel": "เสียสละ",
    "difficulty": "hard",
    "icon": "♛",
    "fen": "6k1/5ppp/8/8/8/6Q1/5PPP/4R1K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาตใน 2 ตา",
    "hint": "Qxg7+",
    "solution": [
      {
        "from": "g3",
        "to": "g7"
      },
      {
        "from": "g8",
        "to": "g7"
      },
      {
        "from": "e1",
        "to": "e8"
      }
    ]
  },
  {
    "id": "tactic-scholar",
    "title": "Scholar's mate",
    "theme": "tactic",
    "themeLabel": "แท็กติก",
    "difficulty": "easy",
    "icon": "🎯",
    "fen": "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4",
    "prompt": "ขาวเดิน — ชนะทันที",
    "hint": "Qxf7#",
    "solution": [
      {
        "from": "h5",
        "to": "f7"
      }
    ]
  },
  {
    "id": "tactic-re8-mate",
    "title": "เรือ e8#",
    "theme": "tactic",
    "themeLabel": "แท็กติก",
    "difficulty": "medium",
    "icon": "♜",
    "fen": "4r1k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "Re8#",
    "solution": [
      {
        "from": "e1",
        "to": "e8"
      }
    ]
  },
  {
    "id": "pin-bishop-b5",
    "title": "พินบิชอป b5",
    "theme": "pin",
    "themeLabel": "พิน",
    "difficulty": "medium",
    "icon": "📌",
    "fen": "r1bqk2r/pppp1ppp/2n2n2/4p3/1PB1P3/8/PP1P1PPP/RNBQK1NR w KQkq - 2 4",
    "prompt": "ขาวเดิน — พินม้า c6",
    "hint": "Bb5",
    "solution": [
      {
        "from": "c4",
        "to": "b5"
      }
    ]
  },
  {
    "id": "black-mate-qh2",
    "title": "ดำรุมฆาต qh2",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♚",
    "fen": "6k1/8/8/8/8/8/6PP/6qK b - - 0 1",
    "prompt": "ดำเดิน — รุมฆาต",
    "hint": "g1→h2",
    "solution": [
      {
        "from": "g1",
        "to": "h2"
      }
    ]
  },
  {
    "id": "q-d3-d8",
    "title": "d3→d8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♟️",
    "fen": "6k1/5ppp/8/8/8/3Q4/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "d3→d8",
    "solution": [
      {
        "from": "d3",
        "to": "d8"
      }
    ]
  },
  {
    "id": "q-a3-a8",
    "title": "a3→a8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♟️",
    "fen": "6k1/5ppp/8/8/8/Q7/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "a3→a8",
    "solution": [
      {
        "from": "a3",
        "to": "a8"
      }
    ]
  },
  {
    "id": "q-c4-c8",
    "title": "c4→c8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♟️",
    "fen": "6k1/5ppp/8/8/2Q5/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "c4→c8",
    "solution": [
      {
        "from": "c4",
        "to": "c8"
      }
    ]
  },
  {
    "id": "r-a8-7k",
    "title": "a1→a8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♟️",
    "fen": "7k/5ppp/8/8/8/8/6PP/R5K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "a1→a8",
    "solution": [
      {
        "from": "a1",
        "to": "a8"
      }
    ]
  },
  {
    "id": "q-e5-e8",
    "title": "e5→e8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/4Q3/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "e5→e8",
    "solution": [
      {
        "from": "e5",
        "to": "e8"
      }
    ]
  },
  {
    "id": "q-d6-d8",
    "title": "d6→d8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/3Q4/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "d6→d8",
    "solution": [
      {
        "from": "d6",
        "to": "d8"
      }
    ]
  },
  {
    "id": "q-c6-c8",
    "title": "c6→c8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/2Q5/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "c6→c8",
    "solution": [
      {
        "from": "c6",
        "to": "c8"
      }
    ]
  },
  {
    "id": "q-b6-b8",
    "title": "b6→b8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/1Q6/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "b6→b8",
    "solution": [
      {
        "from": "b6",
        "to": "b8"
      }
    ]
  },
  {
    "id": "q-e6-e8",
    "title": "e6→e8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/4Q3/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "e6→e8",
    "solution": [
      {
        "from": "e6",
        "to": "e8"
      }
    ]
  },
  {
    "id": "b-ac8",
    "title": "c6→a8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "hard",
    "icon": "♗",
    "fen": "1k6/8/2B5/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "c6→a8",
    "solution": [
      {
        "from": "c6",
        "to": "a8"
      }
    ]
  },
  {
    "id": "n-c6-d8",
    "title": "c6→d8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "hard",
    "icon": "♞",
    "fen": "1k6/8/2N5/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "c6→d8",
    "solution": [
      {
        "from": "c6",
        "to": "d8"
      }
    ]
  },
  {
    "id": "n-f6-g8",
    "title": "f6→g8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "6k1/5ppp/5N2/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "f6→g8",
    "solution": [
      {
        "from": "f6",
        "to": "g8"
      }
    ]
  },
  {
    "id": "fork-nd5",
    "title": "d4→f5",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4k3/8/3n4/8/3N4/8/8/4K3 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "d4→f5",
    "solution": [
      {
        "from": "d4",
        "to": "f5"
      }
    ]
  },
  {
    "id": "fork-nc3",
    "title": "c4→d6",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4k3/8/3r4/8/2N5/8/8/4K3 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "c4→d6",
    "solution": [
      {
        "from": "c4",
        "to": "d6"
      }
    ]
  },
  {
    "id": "fork-na4",
    "title": "c4→e5",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4k3/8/8/4r3/2N5/8/8/4K3 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "c4→e5",
    "solution": [
      {
        "from": "c4",
        "to": "e5"
      }
    ]
  },
  {
    "id": "pin-rd8",
    "title": "d1→d8",
    "theme": "tactic",
    "themeLabel": "แท็กติก",
    "difficulty": "medium",
    "icon": "♜",
    "fen": "4r1k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "d1→d8",
    "solution": [
      {
        "from": "d1",
        "to": "d8"
      }
    ]
  },
  {
    "id": "disc-bh3",
    "title": "e1→e8",
    "theme": "tactic",
    "themeLabel": "แท็กติก",
    "difficulty": "medium",
    "icon": "♜",
    "fen": "4r1k1/5ppp/5B2/8/8/8/5PPP/4R1K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "e1→e8",
    "solution": [
      {
        "from": "e1",
        "to": "e8"
      }
    ]
  },
  {
    "id": "win-qxd8",
    "title": "d4→d8",
    "theme": "tactic",
    "themeLabel": "แท็กติก",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "4r1k1/5ppp/8/8/3Q4/8/5PPP/5RK1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "d4→d8",
    "solution": [
      {
        "from": "d4",
        "to": "d8"
      }
    ]
  },
  {
    "id": "b-qc2",
    "title": "b2→c2",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♚",
    "fen": "6k1/8/8/8/8/8/1q6/6K1 b - - 0 1",
    "prompt": "ดำเดิน — หาตาที่ดีที่สุด",
    "hint": "b2→c2",
    "solution": [
      {
        "from": "b2",
        "to": "c2"
      }
    ]
  },
  {
    "id": "b-qg2",
    "title": "f1→g2",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♚",
    "fen": "6k1/8/8/8/8/8/6PP/5q1K b - - 0 1",
    "prompt": "ดำเดิน — หาตาที่ดีที่สุด",
    "hint": "f1→g2",
    "solution": [
      {
        "from": "f1",
        "to": "g2"
      }
    ]
  },
  {
    "id": "promo-g7",
    "title": "g6→g7",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "easy",
    "icon": "♙",
    "fen": "8/8/6P1/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "g6→g7",
    "solution": [
      {
        "from": "g6",
        "to": "g7"
      }
    ]
  },
  {
    "id": "promo-g8n",
    "title": "g7→g8",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/6P1/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "g7→g8",
    "solution": [
      {
        "from": "g7",
        "to": "g8",
        "promotion": "n"
      }
    ]
  },
  {
    "id": "b-e6-c8",
    "title": "e6→c8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "hard",
    "icon": "♗",
    "fen": "6k1/5ppp/4B3/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "e6→c8",
    "solution": [
      {
        "from": "e6",
        "to": "c8"
      }
    ]
  },
  {
    "id": "b-c3-h7",
    "title": "f5→h7",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♗",
    "fen": "6k1/5ppp/8/5B2/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "f5→h7",
    "solution": [
      {
        "from": "f5",
        "to": "h7"
      }
    ]
  },
  {
    "id": "b-f3-h5",
    "title": "f3→h5",
    "theme": "tactic",
    "themeLabel": "แท็กติก",
    "difficulty": "medium",
    "icon": "♗",
    "fen": "6k1/5ppp/8/8/8/5B2/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "f3→h5",
    "solution": [
      {
        "from": "f3",
        "to": "h5"
      }
    ]
  },
  {
    "id": "r-a8-7k2",
    "title": "a1→a8",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♜",
    "fen": "7k/6pp/8/8/8/8/6PP/R5K1 w - - 0 1",
    "prompt": "ขาวเดิน — หาตาที่ดีที่สุด",
    "hint": "a1→a8",
    "solution": [
      {
        "from": "a1",
        "to": "a8"
      }
    ]
  }
];

const STORAGE_KEY = "chess_puzzles_completed";

export function getCompletedPuzzles() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
  } catch {
    return [];
  }
}

export function markPuzzleComplete(puzzleId) {
  const done = getCompletedPuzzles();
  if (!done.includes(puzzleId)) {
    done.push(puzzleId);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(done));
  }
}

export function isPuzzleComplete(puzzleId) {
  return getCompletedPuzzles().includes(puzzleId);
}

export const THEME_LABELS = {
  mate: "รุมฆาต",
  fork: "ส้อม",
  pin: "พิน / เสียบ",
  tactic: "แท็กติก",
  sacrifice: "เสียสละ",
  promotion: "เดินเบี้ย",
};

export const DIFFICULTY_LABELS = {
  easy: "ง่าย",
  medium: "ปานกลาง",
  hard: "ยาก",
};
