/**
 * Tactical puzzles — generated by build-puzzles.mjs (do not edit by hand)
 * Total: 50 puzzles
 */

export const puzzles = [
  {
    "id": "rook-mate-a",
    "title": "เรือ a8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♜",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "a1→a8",
    "solution": [
      {
        "from": "a1",
        "to": "a8"
      }
    ]
  },
  {
    "id": "rook-mate-d",
    "title": "เรือ d8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♜",
    "fen": "6k1/5ppp/8/8/8/8/4P1PP/3R2K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "d1→d8",
    "solution": [
      {
        "from": "d1",
        "to": "d8"
      }
    ]
  },
  {
    "id": "queen-mate-d8",
    "title": "ควีน d8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "d1→d8",
    "solution": [
      {
        "from": "d1",
        "to": "d8"
      }
    ]
  },
  {
    "id": "queen-mate-a8",
    "title": "ควีน a8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/8/6PP/Q5K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "a1→a8",
    "solution": [
      {
        "from": "a1",
        "to": "a8"
      }
    ]
  },
  {
    "id": "queen-mate-e8",
    "title": "ควีน e8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/4Q1K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "e1→e8",
    "solution": [
      {
        "from": "e1",
        "to": "e8"
      }
    ]
  },
  {
    "id": "q-d3-d8",
    "title": "ควีน d3→d8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/3Q4/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "d3→d8",
    "solution": [
      {
        "from": "d3",
        "to": "d8"
      }
    ]
  },
  {
    "id": "q-a3-a8",
    "title": "ควีน a3→a8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/Q7/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "a3→a8",
    "solution": [
      {
        "from": "a3",
        "to": "a8"
      }
    ]
  },
  {
    "id": "q-c4-c8",
    "title": "ควีน c4→c8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/2Q5/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "c4→c8",
    "solution": [
      {
        "from": "c4",
        "to": "c8"
      }
    ]
  },
  {
    "id": "q-e5-e8",
    "title": "ควีน e5→e8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/8/4Q3/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "e5→e8",
    "solution": [
      {
        "from": "e5",
        "to": "e8"
      }
    ]
  },
  {
    "id": "q-d6-d8",
    "title": "ควีน d6→d8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/3Q4/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "d6→d8",
    "solution": [
      {
        "from": "d6",
        "to": "d8"
      }
    ]
  },
  {
    "id": "q-c6-c8",
    "title": "ควีน c6→c8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/2Q5/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "c6→c8",
    "solution": [
      {
        "from": "c6",
        "to": "c8"
      }
    ]
  },
  {
    "id": "q-b6-b8",
    "title": "ควีน b6→b8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/1Q6/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "b6→b8",
    "solution": [
      {
        "from": "b6",
        "to": "b8"
      }
    ]
  },
  {
    "id": "q-e6-e8",
    "title": "ควีน e6→e8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♕",
    "fen": "6k1/5ppp/4Q3/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "e6→e8",
    "solution": [
      {
        "from": "e6",
        "to": "e8"
      }
    ]
  },
  {
    "id": "r-a8-7k",
    "title": "เรือ a8# (มุม)",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♜",
    "fen": "7k/5ppp/8/8/8/8/6PP/R5K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "a1→a8",
    "solution": [
      {
        "from": "a1",
        "to": "a8"
      }
    ]
  },
  {
    "id": "r-a8-7k2",
    "title": "เรือ a8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "easy",
    "icon": "♜",
    "fen": "7k/6pp/8/8/8/8/6PP/R5K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "a1→a8",
    "solution": [
      {
        "from": "a1",
        "to": "a8"
      }
    ]
  },
  {
    "id": "queen-mate-h8-corner",
    "title": "ควีน d8# (มุม)",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "7k/5ppp/5Q2/8/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "Qd8#",
    "solution": [
      {
        "from": "f6",
        "to": "d8"
      }
    ]
  },
  {
    "id": "tactic-re8-mate",
    "title": "เรือ xe8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♜",
    "fen": "4r1k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "e1→e8",
    "solution": [
      {
        "from": "e1",
        "to": "e8"
      }
    ]
  },
  {
    "id": "piece-mate-nf7",
    "title": "ม้า f7#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♟️",
    "fen": "6rk/5ppp/8/6N1/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "g5→f7",
    "solution": [
      {
        "from": "g5",
        "to": "f7"
      }
    ]
  },
  {
    "id": "mate2-queen-box",
    "title": "รุมฆาตควีน 2 ตา",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/4Q1K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาตใน 2 ตา",
    "hint": "Qe7+ แล้วตามด้วยรุมฆาต",
    "solution": [
      {
        "from": "e1",
        "to": "e7"
      },
      {
        "from": "g8",
        "to": "h8"
      },
      {
        "from": "e7",
        "to": "f8"
      }
    ]
  },
  {
    "id": "mate2-rook-7th",
    "title": "รุมฆาตเรือ 2 ตา",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♜",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาตใน 2 ตา",
    "hint": "Re7+ แล้ว Re8#",
    "solution": [
      {
        "from": "e1",
        "to": "e7"
      },
      {
        "from": "g8",
        "to": "h8"
      },
      {
        "from": "e7",
        "to": "e8"
      }
    ]
  },
  {
    "id": "tactic-scholar",
    "title": "Scholar's mate",
    "theme": "tactic",
    "themeLabel": "แท็กติก",
    "difficulty": "easy",
    "icon": "🎯",
    "fen": "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4",
    "prompt": "ขาวเดิน — รุมฆาตทันที",
    "hint": "Qxf7#",
    "solution": [
      {
        "from": "h5",
        "to": "f7"
      }
    ]
  },
  {
    "id": "fork-nc7",
    "title": "ม้าส้อม c7",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "1k6/r7/8/1N6/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "ม้าส้อมคิงกับเรือ",
    "solution": [
      {
        "from": "b5",
        "to": "c7"
      }
    ]
  },
  {
    "id": "fork-ne5",
    "title": "ม้าส้อม e5",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4k3/8/8/4r3/8/5N2/8/4K2R w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "ม้าส้อมคิงกับเรือ",
    "solution": [
      {
        "from": "f3",
        "to": "e5"
      }
    ]
  },
  {
    "id": "fork-qd5",
    "title": "ควีนส้อม d5",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4r1k1/5ppp/8/8/3Q4/8/5PPP/5RK1 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "ควีนส้อมคิงกับเรือ",
    "solution": [
      {
        "from": "d4",
        "to": "d5"
      }
    ]
  },
  {
    "id": "fork-nd5",
    "title": "ม้าส้อม f5",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4k3/8/3n4/8/3N4/8/8/4K3 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "ม้าส้อมม้ากับคิง",
    "solution": [
      {
        "from": "d4",
        "to": "f5"
      }
    ]
  },
  {
    "id": "fork-nc3",
    "title": "ม้าส้อม d6",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4k3/8/3r4/8/2N5/8/8/4K3 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "ม้าส้อมเรือกับคิง",
    "solution": [
      {
        "from": "c4",
        "to": "d6"
      }
    ]
  },
  {
    "id": "fork-na4",
    "title": "ม้าส้อม e5",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4k3/8/8/4r3/2N5/8/8/4K3 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "ม้าส้อมเรือกับคิง",
    "solution": [
      {
        "from": "c4",
        "to": "e5"
      }
    ]
  },
  {
    "id": "pin-bishop-b5",
    "title": "พินบิชอป b5",
    "theme": "pin",
    "themeLabel": "พิน",
    "difficulty": "medium",
    "icon": "📌",
    "fen": "r1bqk2r/pppp1ppp/2n2n2/4p3/1PB1P3/8/PP1P1PPP/RNBQK1NR w KQkq - 2 4",
    "prompt": "ขาวเดิน — พินม้า c6",
    "hint": "Bb5",
    "solution": [
      {
        "from": "c4",
        "to": "b5"
      }
    ]
  },
  {
    "id": "pin-rd8",
    "title": "เรือ x d8 ชนะเรือ",
    "theme": "tactic",
    "themeLabel": "แท็กติก",
    "difficulty": "medium",
    "icon": "♜",
    "fen": "4r1k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "Rxd8",
    "solution": [
      {
        "from": "d1",
        "to": "d8"
      }
    ]
  },
  {
    "id": "win-qxd8",
    "title": "ควีน x d8 ชนะเรือ",
    "theme": "tactic",
    "themeLabel": "แท็กติก",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "4r1k1/5ppp/8/8/3Q4/8/5PPP/5RK1 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "Qxd8",
    "solution": [
      {
        "from": "d4",
        "to": "d8"
      }
    ]
  },
  {
    "id": "promo-e8q",
    "title": "เดินเบี้ย e8=ควีน",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/4P3/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "e7→e8=q",
    "solution": [
      {
        "from": "e7",
        "to": "e8",
        "promotion": "q"
      }
    ]
  },
  {
    "id": "promo-h8r",
    "title": "เดินเบี้ย h8=เรือ",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/7P/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "h7→h8=r",
    "solution": [
      {
        "from": "h7",
        "to": "h8",
        "promotion": "r"
      }
    ]
  },
  {
    "id": "promo-b8q",
    "title": "เดินเบี้ย b8=ควีน",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/1P6/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "b7→b8=q",
    "solution": [
      {
        "from": "b7",
        "to": "b8",
        "promotion": "q"
      }
    ]
  },
  {
    "id": "promo-c8q",
    "title": "เดินเบี้ย c8=ควีน",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/2P5/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "c7→c8=q",
    "solution": [
      {
        "from": "c7",
        "to": "c8",
        "promotion": "q"
      }
    ]
  },
  {
    "id": "promo-d8q",
    "title": "เดินเบี้ย d8=ควีน",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/3P4/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "d7→d8=q",
    "solution": [
      {
        "from": "d7",
        "to": "d8",
        "promotion": "q"
      }
    ]
  },
  {
    "id": "promo-g8n",
    "title": "เดินเบี้ย g8=ม้า",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "medium",
    "icon": "♙",
    "fen": "8/6P1/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "g7→g8=n",
    "solution": [
      {
        "from": "g7",
        "to": "g8",
        "promotion": "n"
      }
    ]
  },
  {
    "id": "mate2-queen-f8",
    "title": "รุมฆาตควีน 2 ตา",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/4Q1K1 w - - 0 1",
    "hint": "Qe7+ แล้ว Qf8#",
    "solution": [
      {
        "from": "e1",
        "to": "e7"
      },
      {
        "from": "g8",
        "to": "h8"
      },
      {
        "from": "e7",
        "to": "e8"
      }
    ],
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "prompt": "ขาวเดิน — รุมฆาตใน 2 ตา"
  },
  {
    "id": "mate-r-e2-e8",
    "title": "e3→e8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♟️",
    "fen": "6k1/5ppp/8/8/8/4R3/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "e3→e8",
    "solution": [
      {
        "from": "e3",
        "to": "e8"
      }
    ]
  },
  {
    "id": "mate-q-d5-d8",
    "title": "ควีน d5→d8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/8/3Q4/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "d5→d8",
    "solution": [
      {
        "from": "d5",
        "to": "d8"
      }
    ]
  },
  {
    "id": "mate-q-a5-a8",
    "title": "ควีน a5→a8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/8/Q7/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "a5→a8",
    "solution": [
      {
        "from": "a5",
        "to": "a8"
      }
    ]
  },
  {
    "id": "mate2-queen-d8",
    "title": "รุมฆาตควีน 2 ตา (d8)",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/4Q1K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาตใน 2 ตา",
    "hint": "Qe7+ แล้ว Qd8#",
    "solution": [
      {
        "from": "e1",
        "to": "e7"
      },
      {
        "from": "g8",
        "to": "h8"
      },
      {
        "from": "e7",
        "to": "d8"
      }
    ]
  },
  {
    "id": "fork-qe6",
    "title": "ควีนส้อม e6",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "4k3/8/4r3/8/8/4Q3/8/4K3 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "Qe6 ส้อมคิงกับเรือ",
    "solution": [
      {
        "from": "e3",
        "to": "e6"
      }
    ]
  },
  {
    "id": "promo-a8q",
    "title": "เดินเบี้ย a8=ควีน",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "easy",
    "icon": "♙",
    "fen": "8/P7/8/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยแล้วชนะ",
    "hint": "a8=ควีน",
    "solution": [
      {
        "from": "a7",
        "to": "a8",
        "promotion": "q"
      }
    ]
  },
  {
    "id": "promo-g6-g7",
    "title": "เดินเบี้ย g7",
    "theme": "promotion",
    "themeLabel": "เดินเบี้ย",
    "difficulty": "easy",
    "icon": "♙",
    "fen": "8/8/6P1/8/8/8/8/4K2k w - - 0 1",
    "prompt": "ขาวเดิน — เดินเบี้ยชนะ",
    "hint": "g6-g7",
    "solution": [
      {
        "from": "g6",
        "to": "g7"
      }
    ]
  },
  {
    "id": "mate2-queen-d7",
    "title": "รุมฆาตควีน 2 ตา (d7)",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาตใน 2 ตา",
    "hint": "Qd7+ แล้ว Qd8#",
    "solution": [
      {
        "from": "d1",
        "to": "d7"
      },
      {
        "from": "g8",
        "to": "h8"
      },
      {
        "from": "d7",
        "to": "d8"
      }
    ]
  },
  {
    "id": "mate-q-c5-c8",
    "title": "ควีน c5→c8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/8/2Q5/8/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "c5→c8",
    "solution": [
      {
        "from": "c5",
        "to": "c8"
      }
    ]
  },
  {
    "id": "mate-q-e4-e8",
    "title": "ควีน e4→e8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/4Q3/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "e4→e8",
    "solution": [
      {
        "from": "e4",
        "to": "e8"
      }
    ]
  },
  {
    "id": "mate-q-b4-b8",
    "title": "ควีน b4→b8#",
    "theme": "mate",
    "themeLabel": "รุมฆาต",
    "difficulty": "medium",
    "icon": "♕",
    "fen": "6k1/5ppp/8/8/1Q6/8/6PP/6K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "b4→b8",
    "solution": [
      {
        "from": "b4",
        "to": "b8"
      }
    ]
  },
  {
    "id": "fork-nd7",
    "title": "ม้าส้อม d7",
    "theme": "fork",
    "themeLabel": "ส้อม",
    "difficulty": "medium",
    "icon": "♞",
    "fen": "4k3/8/3r4/8/3N4/8/8/4K3 w - - 0 1",
    "prompt": "ขาวเดิน — ชนะหมาก",
    "hint": "Nc6 ส้อมเรือกับคิง",
    "solution": [
      {
        "from": "d4",
        "to": "c6"
      }
    ]
  },
  {
    "id": "tactic-discovered-e8",
    "title": "เรือ xe8# (เปิดลาย)",
    "theme": "tactic",
    "themeLabel": "แท็กติก",
    "difficulty": "medium",
    "icon": "♜",
    "fen": "4r1k1/5ppp/5B2/8/8/8/5PPP/4R1K1 w - - 0 1",
    "prompt": "ขาวเดิน — รุมฆาต",
    "hint": "Rxe8#",
    "solution": [
      {
        "from": "e1",
        "to": "e8"
      }
    ]
  }
];

const STORAGE_KEY = "chess_puzzles_completed";

export function getCompletedPuzzles() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
  } catch {
    return [];
  }
}

export function markPuzzleComplete(puzzleId) {
  const done = getCompletedPuzzles();
  if (!done.includes(puzzleId)) {
    done.push(puzzleId);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(done));
  }
}

export function isPuzzleComplete(puzzleId) {
  return getCompletedPuzzles().includes(puzzleId);
}

export const THEME_LABELS = {
  mate: "รุมฆาต",
  fork: "ส้อม",
  pin: "พิน / เสียบ",
  tactic: "แท็กติก",
  sacrifice: "เสียสละ",
  promotion: "เดินเบี้ย",
};

export const DIFFICULTY_LABELS = {
  easy: "ง่าย",
  medium: "ปานกลาง",
  hard: "ยาก",
};
